server:
  port: 9000

spring:
  application:
    name: Fridge Tracker

  datasource:
    url: jdbc:postgresql://localhost:5432/fridge_tracker
    username: fridge_tracker_user
    password: zMONnm58juGG9Y87q6FYyRWs
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    url: /docs/openapi.yaml

frontend-url: http://localhost:3000

jwt:
  secret: A6O3gSa8dI5Z3KjgJDGYEdYGxlIeriAgcoekwfHtzyrUv2N4vD
  accessExpirationMs: 900000    # 15 minutes
  refreshExpirationMs: 86400000 # 1 day
  refreshTokenExpiry:
    cron: "0 0 * * * *"

